"""Initial migration with all metadata tables

Revision ID: 8b5b30923eb2
Revises: 
Create Date: 2026-07-25 22:21:32.765212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b5b30923eb2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apex_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('alias', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apex_applications_alias'), 'apex_applications', ['alias'], unique=True)
    op.create_index(op.f('ix_apex_applications_id'), 'apex_applications', ['id'], unique=False)
    op.create_table('apex_lovs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lov_name', sa.String(length=255), nullable=False),
    sa.Column('lov_definition', sa.Text(), nullable=True),
    sa.Column('is_static', sa.Boolean(), nullable=True),
    sa.Column('display_extra', sa.Boolean(), nullable=True),
    sa.Column('translation_applicable', sa.Boolean(), nullable=True),
    sa.Column('is_translatable', sa.Boolean(), nullable=True),
    sa.Column('static_values', sa.Text(), nullable=True),
    sa.Column('is_enterable', sa.Boolean(), nullable=True),
    sa.Column('show_null_value', sa.Boolean(), nullable=True),
    sa.Column('null_text', sa.String(length=255), nullable=True),
    sa.Column('null_value', sa.String(length=255), nullable=True),
    sa.Column('apex_item_height', sa.Integer(), nullable=True),
    sa.Column('apex_item_width', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lov_name')
    )
    op.create_index(op.f('ix_apex_lovs_id'), 'apex_lovs', ['id'], unique=False)
    op.create_table('apex_session_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('item_value', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apex_session_state_id'), 'apex_session_state', ['id'], unique=False)
    op.create_index(op.f('ix_apex_session_state_page_id'), 'apex_session_state', ['page_id'], unique=False)
    op.create_index(op.f('ix_apex_session_state_session_id'), 'apex_session_state', ['session_id'], unique=False)
    op.create_index('ux_session_item', 'apex_session_state', ['session_id', 'item_name'], unique=True)
    op.create_table('apex_workspace_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('administrator_role', sa.String(length=50), nullable=True),
    sa.Column('account_expiry_date', sa.DateTime(), nullable=True),
    sa.Column('account_locked', sa.Boolean(), nullable=True),
    sa.Column('failed_access_attempts', sa.Integer(), nullable=True),
    sa.Column('change_password_on_first_use', sa.Boolean(), nullable=True),
    sa.Column('first_name_phonetic', sa.String(length=255), nullable=True),
    sa.Column('last_name_phonetic', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_apex_workspace_users_id'), 'apex_workspace_users', ['id'], unique=False)
    op.create_table('apex_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('alias', sa.String(length=100), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['apex_applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apex_pages_alias'), 'apex_pages', ['alias'], unique=False)
    op.create_index(op.f('ix_apex_pages_id'), 'apex_pages', ['id'], unique=False)
    op.create_table('apex_page_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('alias', sa.String(length=100), nullable=True),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('placeholder', sa.String(length=255), nullable=True),
    sa.Column('default_value', sa.String(length=255), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['apex_pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apex_page_items_id'), 'apex_page_items', ['id'], unique=False)
    op.create_table('apex_page_processes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('process_type', sa.String(length=50), nullable=False),
    sa.Column('process_code', sa.Text(), nullable=True),
    sa.Column('execution_sequence', sa.Integer(), nullable=True),
    sa.Column('execution_point', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['apex_pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apex_page_processes_id'), 'apex_page_processes', ['id'], unique=False)
    op.create_table('apex_regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('region_type', sa.String(length=50), nullable=False),
    sa.Column('template_options', sa.JSON(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['apex_pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apex_regions_id'), 'apex_regions', ['id'], unique=False)
    op.create_table('apex_validations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('validation_type', sa.String(length=50), nullable=False),
    sa.Column('validation_expression', sa.Text(), nullable=True),
    sa.Column('error_message', sa.String(length=4000), nullable=True),
    sa.Column('when_button_pressed', sa.String(length=255), nullable=True),
    sa.Column('condition_type', sa.String(length=255), nullable=True),
    sa.Column('condition_expression', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['apex_pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apex_validations_id'), 'apex_validations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_apex_validations_id'), table_name='apex_validations')
    op.drop_table('apex_validations')
    op.drop_index(op.f('ix_apex_regions_id'), table_name='apex_regions')
    op.drop_table('apex_regions')
    op.drop_index(op.f('ix_apex_page_processes_id'), table_name='apex_page_processes')
    op.drop_table('apex_page_processes')
    op.drop_index(op.f('ix_apex_page_items_id'), table_name='apex_page_items')
    op.drop_table('apex_page_items')
    op.drop_index(op.f('ix_apex_pages_id'), table_name='apex_pages')
    op.drop_index(op.f('ix_apex_pages_alias'), table_name='apex_pages')
    op.drop_table('apex_pages')
    op.drop_index(op.f('ix_apex_workspace_users_id'), table_name='apex_workspace_users')
    op.drop_table('apex_workspace_users')
    op.drop_index('ux_session_item', table_name='apex_session_state')
    op.drop_index(op.f('ix_apex_session_state_session_id'), table_name='apex_session_state')
    op.drop_index(op.f('ix_apex_session_state_page_id'), table_name='apex_session_state')
    op.drop_index(op.f('ix_apex_session_state_id'), table_name='apex_session_state')
    op.drop_table('apex_session_state')
    op.drop_index(op.f('ix_apex_lovs_id'), table_name='apex_lovs')
    op.drop_table('apex_lovs')
    op.drop_index(op.f('ix_apex_applications_id'), table_name='apex_applications')
    op.drop_index(op.f('ix_apex_applications_alias'), table_name='apex_applications')
    op.drop_table('apex_applications')
    # ### end Alembic commands ###
