"""Add sessions table and fix session state foreign key

Revision ID: 9c8d7f012c3a
Revises: 8b5b30923eb2
Create Date: 2026-07-26 04:50:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c8d7f012c3a'
down_revision: Union[str, None] = '8b5b30923eb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apex_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['apex_applications.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['apex_workspace_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apex_sessions_application_id'), 'apex_sessions', ['application_id'], unique=False)
    op.create_index(op.f('ix_apex_sessions_id'), 'apex_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_apex_sessions_session_id'), 'apex_sessions', ['session_id'], unique=True)
    op.create_index(op.f('ix_apex_sessions_user_id'), 'apex_sessions', ['user_id'], unique=False)

    # Fix the session_state table - change session_id from String to Integer and add FK
    # First, drop the old index on session_id
    op.drop_index('ix_apex_session_state_session_id', table_name='apex_session_state')
    op.drop_index('ux_session_item', table_name='apex_session_state')

    # Alter the session_id column to be Integer
    op.alter_column('apex_session_state', 'session_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Integer(),
               existing_nullable=False)

    # Add foreign key constraint
    op.create_foreign_key(None, 'apex_session_state', 'apex_sessions', ['session_id'], ['id'])

    # Recreate the indexes
    op.create_index(op.f('ix_apex_session_state_session_id'), 'apex_session_state', ['session_id'], unique=False)
    op.create_index('ux_session_page_item', 'apex_session_state', ['session_id', 'page_id', 'item_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop foreign key constraint
    op.drop_constraint(None, 'apex_session_state', type_='foreignkey')

    # Drop indexes
    op.drop_index(op.f('ix_apex_session_state_session_id'), table_name='apex_session_state')
    op.drop_index('ux_session_page_item', table_name='apex_session_state')

    # Alter the session_id column back to String
    op.alter_column('apex_session_state', 'session_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    # Recreate the old indexes
    op.create_index('ux_session_item', 'apex_session_state', ['session_id', 'item_name'], unique=True)
    op.create_index(op.f('ix_apex_session_state_session_id'), 'apex_session_state', ['session_id'], unique=False)

    # Drop the apex_sessions table
    op.drop_index(op.f('ix_apex_sessions_user_id'), table_name='apex_sessions')
    op.drop_index(op.f('ix_apex_sessions_session_id'), table_name='apex_sessions')
    op.drop_index(op.f('ix_apex_sessions_id'), table_name='apex_sessions')
    op.drop_index(op.f('ix_apex_sessions_application_id'), table_name='apex_sessions')
    op.drop_table('apex_sessions')
    # ### end Alembic commands ###