"""Add sessions table and fix session state foreign key

Revision ID: 9c8d7f012c3a
Revises: 8b5b30923eb2
Create Date: 2026-07-26 04:50:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c8d7f012c3a'
down_revision: Union[str, None] = '8b5b30923eb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


FK_SESSION_STATE_SESSION = 'fk_apex_session_state_session_id_apex_sessions'


def _remap_session_state(to_session_id: bool):
    """Rewrite apex_session_state.session_id between the two representations.

    Before this revision the column held the string session id; it now holds
    apex_sessions.id. The values are translated through apex_sessions while it
    still exists, and rows whose session is gone are deleted because they can
    never satisfy the new foreign key.

    to_session_id=True converts string -> id, False converts id -> string.
    """
    connection = op.get_bind()

    sessions = connection.execute(sa.text("SELECT id, session_id FROM apex_sessions")).fetchall()
    if to_session_id:
        mapping = {str(session_id): session_id_pk for session_id_pk, session_id in sessions}
    else:
        # session_id is already a varchar at this point, so the ids read from
        # the table compare as strings.
        mapping = {str(session_id_pk): session_id for session_id_pk, session_id in sessions}

    targets = connection.execute(sa.text("SELECT id, session_id FROM apex_session_state")).fetchall()
    for target_id, current_value in targets:
        replacement = mapping.get(str(current_value))
        if replacement is None:
            # The session this row belonged to no longer exists, so the row can
            # never satisfy the foreign key once the column is an integer.
            connection.execute(
                sa.text("DELETE FROM apex_session_state WHERE id = :id"), {"id": target_id}
            )
        else:
            connection.execute(
                sa.text("UPDATE apex_session_state SET session_id = :value WHERE id = :id"),
                {"id": target_id, "value": str(replacement)},
            )


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apex_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['apex_applications.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['apex_workspace_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apex_sessions_application_id'), 'apex_sessions', ['application_id'], unique=False)
    op.create_index(op.f('ix_apex_sessions_id'), 'apex_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_apex_sessions_session_id'), 'apex_sessions', ['session_id'], unique=True)
    op.create_index(op.f('ix_apex_sessions_user_id'), 'apex_sessions', ['user_id'], unique=False)

    # Fix the session_state table - change session_id from the string session id
    # to the apex_sessions primary key. The values have to be translated first,
    # since the old values are UUID strings and cannot be cast to integers.
    _remap_session_state(to_session_id=True)

    # batch_alter_table emits plain ALTERs on PostgreSQL and recreates the table
    # on SQLite, which cannot ALTER a column type or add a foreign key in place.
    with op.batch_alter_table('apex_session_state', schema=None) as batch_op:
        batch_op.drop_index('ix_apex_session_state_session_id')
        batch_op.drop_index('ux_session_item')

        batch_op.alter_column('session_id',
                   existing_type=sa.VARCHAR(length=255),
                   type_=sa.Integer(),
                   existing_nullable=False,
                   postgresql_using='session_id::integer')

        batch_op.create_foreign_key(
            FK_SESSION_STATE_SESSION, 'apex_sessions', ['session_id'], ['id'])

        batch_op.create_index(op.f('ix_apex_session_state_session_id'), ['session_id'], unique=False)
        batch_op.create_index('ux_session_page_item', ['session_id', 'page_id', 'item_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apex_session_state', schema=None) as batch_op:
        # The foreign key has to go first: it pins session_id to the integer
        # apex_sessions.id and cannot survive the column being a varchar again.
        batch_op.drop_constraint(FK_SESSION_STATE_SESSION, type_='foreignkey')

        batch_op.alter_column('session_id',
                   existing_type=sa.Integer(),
                   type_=sa.VARCHAR(length=255),
                   existing_nullable=False,
                   postgresql_using='session_id::varchar(255)')

    # Now that the column holds strings again, translate the values back while
    # apex_sessions still exists to look the session ids up in.
    _remap_session_state(to_session_id=False)

    with op.batch_alter_table('apex_session_state', schema=None) as batch_op:
        batch_op.drop_index(op.f('ix_apex_session_state_session_id'))
        batch_op.drop_index('ux_session_page_item')

        batch_op.create_index('ux_session_item', ['session_id', 'item_name'], unique=True)
        batch_op.create_index(op.f('ix_apex_session_state_session_id'), ['session_id'], unique=False)

    # Drop the apex_sessions table
    op.drop_index(op.f('ix_apex_sessions_user_id'), table_name='apex_sessions')
    op.drop_index(op.f('ix_apex_sessions_session_id'), table_name='apex_sessions')
    op.drop_index(op.f('ix_apex_sessions_id'), table_name='apex_sessions')
    op.drop_index(op.f('ix_apex_sessions_application_id'), table_name='apex_sessions')
    op.drop_table('apex_sessions')
    # ### end Alembic commands ###