"""
Render Endpoint
Handles rendering of pages for preview.
"""
from fastapi import APIRouter, Depends, HTTPException, status, Request
from fastapi.responses import HTMLResponse
from sqlalchemy.orm import Session
from typing import Optional
from ....db import models
from ....db.session import get_db
from ....core.session.service import SessionService

router = APIRouter(tags=["render"])


def _require_page_session(db: Session, request: Request, page: models.Page) -> None:
    """
    Enforce public/protected page visibility for the simple preview renderer.

    Protected pages require a valid active session bound to the page's
    application. The session may be supplied via ``?session_id=`` or the
    ``miniui_session`` cookie.
    """
    if page.is_public:
        return

    session_id = (request.query_params.get("session_id")
                  or request.cookies.get("miniui_session"))
    if not session_id:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Authentication required to view this page",
        )

    session_service = SessionService(db)
    session = session_service.get_session(session_id)
    if not session:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid or expired session",
        )
    if session.application_id != page.application_id:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Access denied to this page"
        )


@router.get("/app/{appAlias}/{pageNumber}")
async def render_page(
    appAlias: str,
    pageNumber: int,
    request: Request,
    db: Session = Depends(get_db)
):
    """
    Render a page as HTML based on application alias and page number.

    Respects the page's public/protected visibility flag.
    """
    # Find application by alias
    application = db.query(models.Application).filter(models.Application.alias == appAlias).first()
    if not application:
        raise HTTPException(status_code=404, detail="Application not found")

    # Find page by application_id and page_number
    page = db.query(models.Page).filter(
        models.Page.application_id == application.id,
        models.Page.page_number == pageNumber
    ).first()
    if not page:
        raise HTTPException(status_code=404, detail="Page not found")

    # Public/protected enforcement
    _require_page_session(db, request, page)

    # Get regions for this page
    regions = db.query(models.Region).filter(models.Region.page_id == page.id).all()

    # Get items for this page
    items = db.query(models.PageItem).filter(models.PageItem.page_id == page.id).all()

    # Generate HTML
    html_parts = []
    html_parts.append('<!DOCTYPE html>')
    html_parts.append('<html lang="en">')
    html_parts.append('<head>')
    html_parts.append('    <meta charset="UTF-8">')
    html_parts.append(f'    <title>{page.name}</title>')
    html_parts.append('    <meta name="viewport" content="width=device-width, initial-scale=1.0">')
    html_parts.append('</head>')
    html_parts.append('<body>')
    html_parts.append('    <header>')
    html_parts.append(f'        <h1>{page.name}</h1>')
    html_parts.append('    </header>')
    html_parts.append('    <main>')

    # Render regions
    for region in regions:
        html_parts.append(f'        <section class="region region-{region.region_type}" data-region-id="{region.id}">')
        html_parts.append('            <header class="region-header">')
        html_parts.append(f'                <h2>{region.name}</h2>')
        html_parts.append(f'                <span class="region-type">{region.region_type}</span>')
        html_parts.append('            </header>')
        html_parts.append('            <div class="region-body">')

        # TODO: Render items that belong to this region
        # For now, we'll just show all items in the region (not implemented)
        html_parts.append('                <p>Region content goes here</p>')

        html_parts.append('            </div>')
        html_parts.append('        </section>')

    # Render items that are not in any region (if we had region_id on items)
    # Since we don't have region_id on items, we'll just list all items at the end for now
    if items:
        html_parts.append('        <div class="items">')
        html_parts.append('            <h3>Page Items</h3>')
        html_parts.append('            <ul>')
        for item in items:
            html_parts.append(f'                <li>{item.label or item.name} ({item.item_type})</li>')
        html_parts.append('            </ul>')
        html_parts.append('        </div>')

    html_parts.append('    </main>')
    html_parts.append('    <footer>')
    html_parts.append('        <p>Generated by MiniUI Preview</p>')
    html_parts.append('    </footer>')
    html_parts.append('</body>')
    html_parts.append('</html>')

    html_content = '\n'.join(html_parts)

    # Never cache rendered pages: standalone views must show the latest
    # saved state without a manual refresh.
    return HTMLResponse(
        content=html_content,
        status_code=200,
        headers={"Cache-Control": "no-store, max-age=0"},
    )