"""
Render Endpoint
Handles rendering of pages for preview.
"""
from fastapi import APIRouter, Depends, HTTPException, status
from fastapi.responses import HTMLResponse
from sqlalchemy.orm import Session
from typing import List
from .... import models, schemas
from ....db.session import get_db

router = APIRouter(tags=["render"])


@router.get("/app/{appAlias}/{pageNumber}")
async def render_page(
    appAlias: str,
    pageNumber: int,
    db: Session = Depends(get_db)
):
    """
    Render a page as HTML based on application alias and page number.
    """
    # Find application by alias
    application = db.query(models.Application).filter(models.Application.alias == appAlias).first()
    if not application:
        raise HTTPException(status_code=404, detail="Application not found")

    # Find page by application_id and page_number
    page = db.query(models.Page).filter(
        models.Page.application_id == application.id,
        models.Page.page_number == pageNumber
    ).first()
    if not page:
        raise HTTPException(status_code=404, detail="Page not found")

    # Get regions for this page
    regions = db.query(models.Region).filter(models.Region.page_id == page.id).all()

    # Get items for this page
    items = db.query(models.PageItem).filter(models.PageItem.page_id == page.id).all()

    # Generate HTML
    html_parts = []
    html_parts.append('<!DOCTYPE html>')
    html_parts.append('<html lang="en">')
    html_parts.append('<head>')
    html_parts.append('    <meta charset="UTF-8">')
    html_parts.append(f'    <title>{page.title or page.name}</title>')
    html_parts.append(f'    <meta name="viewport" content="width=device-width, initial-scale=1.0">')
    html_parts.append('</head>')
    html_parts.append('<body>')
    html_parts.append(f'    <header>')
    html_parts.append(f'        <h1>{page.name}</h1>')
    html_parts.append(f'    </header>')
    html_parts.append(f'    <main>')

    # Render regions
    for region in regions:
        html_parts.append(f'        <section class="region region-{region.region_type}" data-region-id="{region.id}">')
        html_parts.append(f'            <header class="region-header">')
        html_parts.append(f'                <h2>{region.name}</h2>')
        html_parts.append(f'                <span class="region-type">{region.region_type}</span>')
        html_parts.append(f'            </header>')
        html_parts.append(f'            <div class="region-body">')

        # TODO: Render items that belong to this region
        # For now, we'll just show all items in the region (not implemented)
        html_parts.append(f'                <p>Region content goes here</p>')

        html_parts.append(f'            </div>')
        html_parts.append(f'        </section>')

    # Render items that are not in any region (if we had region_id on items)
    # Since we don't have region_id on items, we'll just list all items at the end for now
    if items:
        html_parts.append(f'        <div class="items">')
        html_parts.append(f'            <h3>Page Items</h3>')
        html_parts.append(f'            <ul>')
        for item in items:
            html_parts.append(f'                <li>{item.label or item.name} ({item.item_type})</li>')
        html_parts.append(f'            </ul>')
        html_parts.append(f'        </div>')

    html_parts.append(f'    </main>')
    html_parts.append(f'    <footer>')
    html_parts.append(f'        <p>Generated by MiniUI Preview</p>')
    html_parts.append(f'    </footer>')
    html_parts.append('</body>')
    html_parts.append('</html>')

    html_content = '\n'.join(html_parts)

    return HTMLResponse(content=html_content, status_code=200)